### ISSUE TITLE
@%+ signs before nicks

### ISSUE THREAD

**Issue by abonforti** [x70b1/irssi-weed#1]
Hi,
would it be possible (and if yes, how) to add the chan signs before the nicknames?

**Comment by x70b1** [comment]
Should be doable. Maybe somewhere [here](https://github.com/x70b1/irssi-weed/blob/master/weed.theme#L34).

`/names` give us already the user mode. So maybe look at [theese lines](https://github.com/x70b1/irssi-weed/blob/master/weed.theme#L74) too.

**Comment by abonforti** [comment]
Is there any documentation available? I am not that much confident about Irssi scripting

**Comment by x70b1** [comment]
Figure it out. There's nothing I can recommend. Probably official docs.
The best thing is to just try it around and find some snippets how others have done it.
